spring:
  application:
    name: eurekaserverudemy

server:
  port: 8761 #porta padrao do eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false #gateway farÃ¡ o registro
